### PR TITLE
Added a spinner when installing packages

### LINKED ISSUE #52: Add spinner during the installation
## 📝 Provide a description of the improvement

When generating the package without `--verbose` option, it takes some time to install the dependencies and do all things that are necessary under the hood. During this time user has no information on what is currently going on. It would be a nice finishing touch to show the user a spinner, to indicate that everything is fine and installation is 'in progress'.

## 📃 Other details

* Node: …
* Npm / Yarn: …
* First affected version: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature (generator): Added a spinner when installing packages. Closes #52.

### CODE REVIEW

**Comment by pomek** [comment]
Demo:

https://user-images.githubusercontent.com/2270764/138110686-c419ffb8-0f76-43ad-9553-1e79f3044bcc.mov

**Comment by pomek** [comment]
How does it behave in terminals? Cmd, Git bash, Powershell?

**Review by psmyrek — APPROVED** [review]
Wow, I'm impressed with how cleverly and simply this has been achieved 🎉 

The spinner does not even flash, but it animates very smoothly in all my terminals:

#### Command Prompt
cmd

#### Git Bash
git bash

#### PowerShell
powershell

For a comparison - this is how a spinner looks like in the crawler, which uses the well-known `ora` package with almost 10 million downloads per week:

**Review by przemyslaw-zan — APPROVED** [review]
Spinner flashing is fixed on my machine, LGTM!

**Pull request merged**
